---
# vars for rpm transport
#Pubic_IP: 58.213.139.100
package_tmp_path: /opt/software
filebeat_rpm: filebeat-5.3.0-x86_64.rpm
filebeat_config_file: /etc/filebeat/filebeat.yml
# vars for filebeat config file
input_type: log
input_logs:
  - /var/log/messages
  - /var/log/secure
  - /var/log/cron
#redis_hosts: 192.168.1.233
#redis_port: 6380
#redis_db: 1
#redis_key: logs_collection
logstash:
  host: log-collect01.shein.com
  ip: 10.168.59.136
